[improve](cloud-deploy) add docs for deploying doris cloud
apache/doris-website pull request #1072
Opened 2024-08-31 14:32 UTC by dataroaring

# Versions 

- [ ] dev
- [ ] 3.0
- [ ] 2.1
- [ ] 2.0

# Languages

- [ ] Chinese
- [ ] English

2024-09-04 11:07 UTC, intelligentfu8 approved these changes

2024-09-18 15:28 UTC, gavinchou commented on docs/compute-storage-decoupled/managing-storage-vault.md
> -| s3.bucket                      | S3 vault parameter                                           | Required          | `sample_bucket_name`          |
missing bucket

2024-09-18 15:49 UTC, gavinchou commented on i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/file-cache.md
> +|/opt/apache/dpris/be/storage/file_cache | file_cache_ttl_cache_size | 0 |
```suggestion
上述例子中指标前缀为 File Cache 的路径, 例如前缀 "_mnt_disk1_gavinchou_debug_doris_cloud_be0_storage_file_cache_" 表示 "/mnt/disk1/gavinchou/debug/doris-cloud/be0_storage_file_cache/"
去掉前缀的部分为统计指标, 比如 "file_cache_cache_size" 表示当前 路径的 File Cache 大小为 26111 字节

下表为全部的指标意义 (一下表示size大小单位均为字节)

指标名称(不包含路径前缀) | 语义
-----|------
file_cache_cache_size | 当前 File Cache 的总大小
file_cache_disposable_queue_cache_size | 当前 disposable 队列的大小
file_cache_disposable_queue_element_count | 当前 disposable 队列里的元素个数
file_cache_disposable_queue_evict_size | 从启动到当前 disposable 队列总共淘汰的数据量大小
file_cache_index_queue_cache_size | 当前 index 队列的大小
file_cache_index_queue_element_count | 当前 index 队列里的元素个数
file_cache_index_queue_evict_size | 从启动到当前 index 队列总共淘汰的数据量大小
file_cache_normal_queue_cache_size | 当前 normal 队列的大小
file_cache_normal_queue_element_count | 当前 normal 队列里的元素个数
file_cache_normal_queue_evict_size | 从启动到当前 normal 队列总共淘汰的数据量大小
file_cache_total_evict_size | 从启动到当前, 整个 File Cache 总共淘汰的数据量大小
file_cache_ttl_cache_evict_size | 从启动到当前 TTL 队列总共淘汰的数据量大小
file_cache_ttl_cache_lru_queue_element_count | 当前 TTL 队列里的元素个数
file_cache_ttl_cache_size | 当前 TTL 队列的大小

```

2024-09-18 18:04 UTC, yagagagaga commented on docs/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-ADD-BACKEND.md
> +    * host1 with port 9020
why not use 9050 in demo

2024-09-18 18:04 UTC, yagagagaga commented on i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-ADD-BACKEND.md
> +    * host1，端口 9020
9020默认是FE 上的 thrift server端口，这里应该改成9050比较好

2024-09-18 18:04 UTC, yagagagaga commented on versioned_docs/version-3.0/sql-manual/sql-statements/Database-Administration-Statements/SET-DEFAULT-STORAGE-VAULT.md
> +SET vault_name DEFAULT STORAGE VAULT
SET vault_name AS DEFAULT STORAGE VAULT

2024-09-18 18:04 UTC, yagagagaga commented on versioned_docs/version-3.0/sql-manual/sql-statements/Database-Administration-Statements/WARM-UP-COMPUTE-GROUP.md
> +   WARM UP COMPUTE GROUP destination_group_name WITH COMPUTE GROUP source_group_name.
Ending with `;` instead of `.`

2024-09-18 18:04 UTC, yagagagaga commented on versioned_docs/version-3.0/sql-manual/sql-statements/Show-Statements/SHOW-CACHE-HOTSPOT.md
> + - [MANAGING FILE CACHE]
```
[MANAGING FILE CACHE](../../../compute-storage-decoupled/file-cache.md)
```

2024-09-19 08:04 UTC, freemandealer requested changes

2024-09-19 08:04 UTC, freemandealer commented on i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/file-cache.md
> +- TTL 类型缓存的后台会有线程异步扫描 TTL 的过期时间。如果过期，则将 TTL 降级为 Normal，并依据上述 Normal 淘汰顺序进行删除。
这里突然出现了 Normal 这个术语，术语使用不一致（上文是 LRU）。

2024-09-19 08:04 UTC, freemandealer commented on i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/file-cache.md
> +下表为全部的指标意义 (一下表示size大小单位均为字节)
```suggestion
下表为全部的指标意义 (以下表示size大小的单位均为字节)
```

2024-09-26 15:06 UTC, yagagagaga requested changes

2024-09-26 15:06 UTC, yagagagaga commented on i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/compilation-and-deployment.md
> +使用以下 SQL 命令添加额外的 FE 节点：
```suggestion
其他节点同样根据上述步骤修改配置文件并启动，使用 mysql 客户端 Master 角色的 FE，并用以下 SQL 命令添加额外的 FE 节点：
```

2024-09-29 09:26 UTC, wangshuo128 requested changes

2024-09-29 09:26 UTC, wangshuo128 commented on docs/compute-storage-decoupled/compilation-and-deployment.md
> +For production environment, please ensure that the total number of Meta Serivie is at least three.
```suggestion
For production environment, please ensure that the total number of Meta Service is at least three.
```

2024-10-09 11:16 UTC, merged